#ifndef _XIMAGE_FORMATS_HPP_____
#define _XIMAGE_FORMATS_HPP_____

// Simple planer formats
#define XIMAGE_FORMAT_PLANAR_BASE 0x00
#define XIMAGE_FORMAT_GRAY (XIMAGE_FORMAT_PLANAR_BASE + 0)
#define XIMAGE_FORMAT_Y (XIMAGE_FORMAT_PLANAR_BASE + 1)
#define XIMAGE_FORMAT_U (XIMAGE_FORMAT_PLANAR_BASE + 2)
#define XIMAGE_FORMAT_V (XIMAGE_FORMAT_PLANAR_BASE + 3)

// RGB formats
#define XIMAGE_RGB_BASE 0x100
#define XIMAGE_FORMAT_RGBX (XIMAGE_RGB_BASE + 0)
#define XIMAGE_FORMAT_BGRX (XIMAGE_RGB_BASE + 1)
#define XIMAGE_FORMAT_XRGB (XIMAGE_RGB_BASE + 2)
#define XIMAGE_FORMAT_XBGR (XIMAGE_RGB_BASE + 3)
#define XIMAGE_FORMAT_RGBA (XIMAGE_RGB_BASE + 4)
#define XIMAGE_FORMAT_BGRA (XIMAGE_RGB_BASE + 5)
#define XIMAGE_FORMAT_ARGB (XIMAGE_RGB_BASE + 6)
#define XIMAGE_FORMAT_ABGR (XIMAGE_RGB_BASE + 7)

// Invalid
#define XIMAGE_FORMAT_INVALID 0xFFFFFFFF

#endif